<a href="https://colab.research.google.com/github/Lakshmimadira/Data-Science-Tutorial/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Arthimatic operations
import numpy as np

first_array=np.array([1,3,5,7])
second_array=np.array([2,4,6,8])
#using the + operator
result1=first_array + second_array
print("using the + operator:",result1)
#using the add() function
result2=np.add(first_array,second_array)
print("using the add() function:",result2)

first_array=np.array([3,9,27,81])
second_array=np.array([2,4,8,16])
#using the - operator
result1=first_array - second_array
print("using the - operator:",result1)
#using the subtract() function
result2=np.subtract(first_array,second_array)
print("using the subtract() function:",result2)

first_array=np.array([1,3,5,7])
second_array=np.array([2,4,6,8])
#using the * operator
result1=first_array * second_array
print("using the * operator:",result1)
#using the multiply() function
result2=np.multiply(first_array,second_array)
print("using the multiply() function:",result2)

first_array=np.array([1,2,3])
second_array=np.array([4,5,6])
#using the / operator
result1=first_array / second_array
print("using the / operator:",result1)
#using the divide() function
result2=np.divide(first_array,second_array)
print("using the divide() function:",result2)

array1=np.array([1,2,3])
#using the ** operator
result1=array1**2
print("using the ** operator:",result1)
#using the power() function
result2=np.power(array1,2)
print("using the power() function:",result2)

first_array=np.array([9,10,20])
second_array=np.array([2,5,7])
#using the % operator
result1=first_array % second_array
print("using the + operator:",result1)
#using the mod() function
result2=np.mod(first_array,second_array)
print("using the mod() function:",result2)


using the + operator: [ 3  7 11 15]
using the add() function: [ 3  7 11 15]
using the - operator: [ 1  5 19 65]
using the subtract() function: [ 1  5 19 65]
using the * operator: [ 2 12 30 56]
using the multiply() function: [ 2 12 30 56]
using the / operator: [0.25 0.4  0.5 ]
using the divide() function: [0.25 0.4  0.5 ]
using the ** operator: [1 4 9]
using the power() function: [1 4 9]
using the + operator: [1 0 6]
using the mod() function: [1 0 6]


In [4]:
import numpy as np

#create an array using np.array()
array1=np.array([1,3,5])
print("np.array():\n",array1)

#create an array filled with zeros using np.zeros()
array2=np.zeros((3,3))
print("\nnp.zeros():\n",array2)

#create an array filled with ones using np.ones()
array3=np.ones((2,4))
print("\nnp.ones():\n",array3)

#create a 1D array
array1=np.array([1,3,5,7,9,11])

#reshape the 1D array into a 2D array
array2=np.reshape(array1,(2,3))

#transpose 2D array
array3=np.transpose(array2)

print("\nOriginal array:\n",array1)
print("\nReshaped array:\n",array2)
print("\nTransposed array:\n",array3)

#create a numpy array
marks=np.array([76,78,81,66,85])

#compute the mean of marks
mean_marks=np.mean(marks)
print("\nmean:",mean_marks)

#compute the median of marks
median_marks=np.median(marks)
print("median:",median_marks)

#find the minimum and maximum marks
min_marks=np.min(marks)
print("minimum marks:",min_marks)
max_marks=np.max(marks)
print("maximum marks:",max_marks)


np.array():
 [1 3 5]

np.zeros():
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

np.ones():
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Original array:
 [ 1  3  5  7  9 11]

Reshaped array:
 [[ 1  3  5]
 [ 7  9 11]]

Transposed array:
 [[ 1  7]
 [ 3  9]
 [ 5 11]]

mean: 77.2
median: 78.0
minimum marks: 66
maximum marks: 85


In [5]:
#logical operations
import numpy as np
array1=np.array([1,2,3])
array2=np.array([3,2,1])

#less than operator
result1=array1<array2
print("array1<array2:",result1)

#greater than operator
result1=array1>array2
print("array1>array2:",result1)

#equal to operator
result3=array1==array2
print("array1==array2:",result1)

#useof less()
result=np.less(array1,array2)
print("using less():",result)

#use of less_equal
result=np.less_equal(array1,array2)
print("using less_equal():",result)

#use of greater()
result=np.greater(array1,array2)
print("using greater():",result)

#use of greater_equal()
result=np.greater_equal(array1,array2)
print("using greater_equal():",result)

#use of equal()
result=np.equal(array1,array2)
print("using equal():",result)

#use of not_equal()
result=np.not_equal(array1,array2)
print("using not_equal():",result)

array1<array2: [ True False False]
array1>array2: [False False  True]
array1==array2: [False False  True]
using less(): [ True False False]
using less_equal(): [ True  True False]
using greater(): [False False  True]
using greater_equal(): [False  True  True]
using equal(): [False  True False]
using not_equal(): [ True False  True]
